// <auto-generated />
using Csharp_periode_4_Groep_24_2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Csharp_periode_4_Groep_24_2025.Migrations
{
    [DbContext(typeof(DbContext24))]
    partial class DbContext24ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Csharp_periode_4_Groep_24_2025.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Activity")
                        .HasColumnType("smallint");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<short>("Diet")
                        .HasColumnType("smallint");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SecurityRequirement")
                        .HasColumnType("smallint");

                    b.Property<short>("SizeClass")
                        .HasColumnType("smallint");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Animals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = (short)1,
                            Diet = (short)3,
                            Name = "Bear",
                            Prey = "Fish",
                            SecurityRequirement = (short)2,
                            SizeClass = (short)5,
                            SpaceRequirement = 300.0,
                            Species = "Bear"
                        },
                        new
                        {
                            Id = 2,
                            Activity = (short)1,
                            Diet = (short)5,
                            Name = "Eagle",
                            Prey = "Fish",
                            SecurityRequirement = (short)1,
                            SizeClass = (short)4,
                            SpaceRequirement = 50.0,
                            Species = "Bird"
                        },
                        new
                        {
                            Id = 3,
                            Activity = (short)3,
                            Diet = (short)2,
                            Name = "Salmon",
                            Prey = "None",
                            SecurityRequirement = (short)1,
                            SizeClass = (short)3,
                            SpaceRequirement = 120.0,
                            Species = "Fish"
                        },
                        new
                        {
                            Id = 4,
                            Activity = (short)1,
                            Diet = (short)1,
                            Name = "Wolf",
                            Prey = "Deer",
                            SecurityRequirement = (short)2,
                            SizeClass = (short)5,
                            SpaceRequirement = 300.0,
                            Species = "Catlike"
                        },
                        new
                        {
                            Id = 5,
                            Activity = (short)2,
                            Diet = (short)5,
                            Name = "Owl",
                            Prey = "Fish",
                            SecurityRequirement = (short)1,
                            SizeClass = (short)4,
                            SpaceRequirement = 200.0,
                            Species = "Bird"
                        });
                });

            modelBuilder.Entity("Csharp_periode_4_Groep_24_2025.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bird"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mammal"
                        });
                });

            modelBuilder.Entity("Csharp_periode_4_Groep_24_2025.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("ClimateClass")
                        .HasColumnType("smallint");

                    b.Property<short>("HabitatType")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Security")
                        .HasColumnType("smallint");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Enclosures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClimateClass = (short)3,
                            HabitatType = (short)2,
                            Name = "Sigma",
                            Security = (short)3,
                            Size = 320.0
                        },
                        new
                        {
                            Id = 2,
                            ClimateClass = (short)1,
                            HabitatType = (short)4,
                            Name = "Delta",
                            Security = (short)1,
                            Size = 200.0
                        },
                        new
                        {
                            Id = 3,
                            ClimateClass = (short)2,
                            HabitatType = (short)8,
                            Name = "Epsilon",
                            Security = (short)1,
                            Size = 240.0
                        },
                        new
                        {
                            Id = 4,
                            ClimateClass = (short)3,
                            HabitatType = (short)8,
                            Name = "Zeta",
                            Security = (short)1,
                            Size = 240.0
                        },
                        new
                        {
                            Id = 5,
                            ClimateClass = (short)0,
                            HabitatType = (short)8,
                            Name = "Gamma",
                            Security = (short)1,
                            Size = 320.0
                        });
                });

            modelBuilder.Entity("Csharp_periode_4_Groep_24_2025.Models.Animal", b =>
                {
                    b.HasOne("Csharp_periode_4_Groep_24_2025.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Csharp_periode_4_Groep_24_2025.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId");

                    b.Navigation("Category");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("Csharp_periode_4_Groep_24_2025.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Csharp_periode_4_Groep_24_2025.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
